sudo: false
language: ruby
addons:
  postgresql: '9.5'
services:
  - postgresql
  - redis-server
rvm:
  - 2.4.0
before_install: gem install bundler -v 1.16.0
script:
  - bundle exec rspec
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec  