default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: qboard_development

production:
  <<: *default
  database: qboard_production
  username: qboard
  password: <%= ENV['QBOARD_DATABASE_PASSWORD'] %>
